Initial 4.1 changes (unified TACC interface).

diff --git a/01_SSH b/01_SSH
--- a/01_SSH
+++ b/01_SSH
@@ -1,23 +1,42 @@
 #!/bin/bash
+# Checks for a specific <code>.pub file and <code> file to
+# be in $HOME/.ssh.  Also, contents of <code>.pub must be
+# in authorized_keys file.
+# SITES should specify a single <code> and <code>.pub in these
+# arrays below (e.g.):
+#  pub_key_files=( id_rsa.pub )
+# priv_key_files=( id_rsa     )
+
+# SITES such as TACC that use multiple keys, but only one type
+# per system should specify multiple keys in the arrays, but
+# only one is expected to be found. 
+
 # 1.) Check permission on ~/.ssh directory
-# 2.) Check permission on ~/.ssh/*_id.pub 
-# 3.) Check permission on ~/.ssh/*_id
+# 2.) Check permission on ~/.ssh/id_*.pub 
+# 3.) Check permission on ~/.ssh/id_
 # 4.) Check permission on ~/.ssh/authorized_keys
 # 5.) Make sure *_id.pub is in authorized_keys
 
-#TODO What if multiple keys?
 #TODO Exist later if 0 keys found (check directory permissions
 #TODO Exist later if OK with multiple keys
 #                                 2025-08-01 Kent Milfeld
 
-  [[ $# != 1 ]] && O=N    #Command line options T=terse,v=Verbose, default Normal
-  [[ $1 == t ]] && O=T
-  [[ $1 == v ]] && O=V
+  [[ $# == 0 ]] && O=N    #Command line options T=terse,v=Verbose, default Normal
+  [[ $1 =~ t ]] && O=T
+  [[ $1 =~ v ]] && O=V
+  [[ ! "$O" =~ [NTV] ]] && echo "USAGE: $0 [-t|-v] # terse|verbose output"
 
   STATUS=0
 
   HPC_OSs=(rocky centos fedora ubuntu debian)
 
+   SSH_DIR=$HOME/.ssh
+   SSH_DIR=$HOME/.ssh_test
+   SSH_DIR=$HOME/.sshx
+   SSH_DIR=$HOME/.ssh_empty
+   SSH_DIR=$HOME/.ssh_mixed
+   SSH_DIR=$HOME/.ssh_multi
+   SSH_DIR=$HOME/.ssh_noauth
    SSH_DIR=$HOME/.ssh
    pub_key_files=( id_ed25519.pub id_rsa.pub id_ecdsa.pub )
   priv_key_files=( id_ed25519     id_rsa     id_ecdsa )
@@ -42,41 +61,61 @@
     [[ `uname -a` =~ Darwin ]] && OS=darwin
   fi
 
-echo "SSH setup"
+
+# [PASS] 01 SSH: found keys with correct permissions
+
+# [PASS] 01 SSH:  keys and permissions
+#           SSH Found files :    (.ssh id_ed25519.pub id_ed25519 authorized_keys)
+#           Permissions OK for:  (.ssh id_ed25519.pub id_ed25519 authorized_keys)
+
+# [PASS] 01 SSH setup
+#            Found directory pub_key.
+#            Found public key id_ed25519.pub
+#            Found private key id_ed25519
+#            Permissions correct for .ssh:            drwx------
+#            Permissions correct for id_ed25519.pub:  -rw-r--r--
+#            Permissions correct for id_ed25519:      -rw-------
+#            Permissions correct for authorized_keys: -rw-------
+
 
 # SSH Directory
 if [[ ! -d $SSH_DIR ]]; then  # Does $HOME/.ssh exist
    unfound=(${filenames[0]})
-   echo " NO \$HOME/.ssh directory found." && exit 1
+   echo " SSH: ERROR, NO \$HOME/.ssh directory found." && exit 1
 else
   found=(${filenames[0]})
-  [[ $O == N ]] || [[ $O == V ]] &&
-  echo " Found ${functions[0]} ${filenames[1]}."
-  
+
+  [[ $O == V ]] &&
+  echo " SSH:  Setup" &&
+  echo " Found ${functions[0]} ${filenames[0]}, will search for key pair."
 fi
 
 # PUBLIC KEY file(s)
 output=`ls $SSH_DIR/*.pub 2>/dev/null`  #pub key
-if [[ $? != 0 ]]; then
-  echo " NO ${functions[1]} Found (of form \*pub)."
-  STATUS=1
-else   #determine key type
+
+if [[ $? == 0 ]]; then  #determine key type
   for file in ${pub_key_files[@]}; do
     [[ $output =~ $file  ]] && pub_keys+=($file)
   done
+  if [[ ${#pub_keys[@]} == 0 ]] && [[ $STATUS == 0 ]]; then
+    STATUS=1
+    nonsite_pub_keys=$(echo $output | sed  's@'$SSH_DIR/'@@g')
+    echo " SSH: NO HPC-SITE required ${functions[1]} FOUND."
+    echo " But, FOUND ${functions[1]}(s) (${nonsite_pub_keys})"
+    exit 1
+  fi
+else
+  echo " SSH: NO HPC-SITE required ${functions[1]} FOUND."
+  echo " (Searched for ${pub_key_files[@]})."
+  exit 1
 fi
 
 if [[ ${#pub_keys[@]}  == 1 ]]; then
   filenames[1]=${pub_keys[0]}
   found+=(${filenames[1]})
 
-  [[ $O == N ]] || [[ $O == V ]] &&
+  [[ $O == V ]]  &&
     echo " Found ${functions[1]} ${filenames[1]}" && pub_key=${pub_keys[0]}
-fi
-if [[ ${#pub_keys[@]} == 0 ]]; then
-  unfound+=(${filenames[1]})
-  skip=(1)
-  echo " NO ${functions[1]} Found (searched: ${pub_key_files[@]})" && STATUS=1
 fi
 
 # PRIVATE KEY file(s)
@@ -89,32 +128,56 @@ if [[ ${#priv_keys[@]}  == 1 ]]; then
   filenames[2]=${priv_keys[0]}
   found+=(${filenames[2]})
 
-  [[ $O == N ]] || [[ $O == V ]] &&
+  if [[ ! ${filenames[1]} =~ ${filenames[2]} ]]; then
+     echo " SSH: ERROR, Priv/Pub keys DO NOT MATCH (${filenames[1]}, ${filenames[2]})."
+     exit 1
+  fi
+
+  [[ $O == V ]] &&
     echo " Found ${functions[2]} ${filenames[2]}" && priv_key=${priv_keys[0]}
-fi
-if [[ ${#priv_keys[@]} == 0 ]]; then
-  unfound+=(${filenames[2]})
-  skip+=(2)
-  echo " NO ${functions[2]} Found (searched: ${priv_key_files[@]})" && STATUS=1
+
+elif [[ ${#priv_keys[@]} == 0 ]]; then
+  echo " SSH: NO HPC-SITE required ${functions[2]} FOUND."
+  echo " (expected to find: ${filenames[1]%%.pub})"
+  exit 1
+else 
+  if [[ ${priv_keys[@]} =~ ${filenames[1]%%.pub} ]]; then
+    filenames[2]=${filenames[1]%%.pub}
+    found+=(${filenames[2]})
+
+    [[ $O == V ]] &&
+    echo " Found multiple priv. keys (${priv_keys[@]}); using ${filenames[1]%%.pub}." 
+  else
+    echo " SSH: NO ${filenames[1]%%.pub} file FOUND for ${filenames[1]}."
+    [[ $O == V ]] &&
+    echo " Multiple Other HPC-SITE required ${functions[2]}(s) FOUND." &&
+    echo " (found ${functions[2]}(s): ${priv_keys[@]} )"
+    exit 1
+  fi
 fi
 
-# AUTHORIZED_KEYS file
+# AUTHORIZED_KEYS file  -- make sure it exists.
 output=`ls $SSH_DIR/${filenames[3]} 2>/dev/null`  #authorized_keys
 if [[ $? != 0 ]]; then
   unfound+=(${filenames[3]})
-  skip+=(3)
-  echo " NO ${functions[3]} file Found."
-  STATUS=1
+
+  echo " SSH: NO ${functions[3]} file Found."
+  echo "      cat ${filenames[2]} > $SSH_DIR/${filenames[3]}" &&
+  echo "      chmod 600  $SSH_DIR/${filenames[3]}"
+  exit 1
 else
   found+=(${filenames[3]})
 fi
 
-if [[ $O == T ]]; then
+if [[ $O == N ]]; then
   flat_found="${found[@]}" flat_unfound="${unfound[@]}"
-  printf  " SSH Found files :    (%s)\n" "$flat_found"
-  [[ ${#unfound[@]} -gt 0 ]] &&
-  printf " SSH NOT Found files: (%s)\n" "$flat_unfound"
+  echo   " SSH: found keys with correct permissions"
+  printf " Found files :        (%s)\n" "$flat_found"
+ #[[ ${#unfound[@]} -gt 0 ]] &&
+ #printf "SSH NOT Found files: (%s)\n" "$flat_unfound"
 fi
+
+#===========================================================
 
 check_perm(){
 
@@ -136,7 +199,7 @@ check_perm(){
   
   
   if [[ $stat_perm == ${perms[$i]} ]]; then
-    [[ $O == N ]] || [[ $O == V ]] &&
+    [[ $O == V ]] &&
     printf " %-40s %s\n"  "Permissions correct for $name:" "${perms[$i]}"
   else
     return_status=1
@@ -148,19 +211,24 @@ check_perm(){
 
 }
 
+# skip used to avoid permission check. Code no exits if file not found
 for i in ${!filenames[@]}; do
-  if [[ ! "${skip[@]}" =~ $i ]]; then
+ #if [[ ! "${skip[@]}" =~ $i ]]; then
     path_name=$SSH_DIR/${filenames[$i]}
     [[ $i == 0 ]] &&  path_name=$SSH_DIR  #Special, the Directory
 
     check_perm ${path_name} ${perms[$i]} ${set_perms[$i]} $O
 
     [[ $return_status != 0 ]] && STATUS=$return_status
-  fi
+ #fi
 done
 
-if [[ $O == T ]] && [[ $STATUS == 0 ]]; then
+if [[ $O == N ]] && [[ $STATUS == 0 ]]; then
    echo " Permissions OK for:  (${filenames[@]})" 
+fi
+
+if [[ $O == T ]] && [[ $STATUS == 0 ]]; then
+   echo " SSH: found keys with correct permissions"
 fi
 
 exit $STATUS
diff --git a/03_Quotas b/03_Quotas
--- a/03_Quotas
+++ b/03_Quotas
@@ -1,190 +1,296 @@
 #!/bin/bash
 
+  [[ $# == 0 ]] && O=N    #Command line options T=terse,v=Verbose, default Normal
+  [[ $1 =~ t ]] && O=T 
+  [[ $1 =~ v ]] && O=V 
+  [[ ! "$O" =~ [NTV] ]] && echo "USAGE: $0 [-t|-v] # terse|verbose output"
 
-[[ $# != 1 ]] && O=N    #Command line options T=terse,v=Verbose, default Normal
-[[ $1 == t ]] && O=T
-[[ $1 == v ]] && O=V
+  STATUS=0
 
-host_name=`hostname -A`
+  HPC_OSs=(rocky centos fedora ubuntu debian)
+  if [[ -f /etc/os-release ]]; then
+    output=$( grep ^ID= /etc/os-release ) #e.g. ID="rocky"
+    eval $output
+    OS=$ID
+    if [[ ! ${HPC_OSs[@]} =~ $OS ]]; then
+       echo " internal ERROR: could not get OS from /etc/os-release"
+       echo "   search list ( ${HPC_OSs[@]} )"
+       exit 1
+    fi  
+  else
+    [[ `uname -a` =~ Darwin ]] && OS=darwin
+  fi  
 
-for sys in ls6 frontera stampede3 vista; do
-  [[ $host_name =~ $sys ]] && AT_TACC=yes TACC_SYS=$sys
-done
+  [[ $OS == darwin ]]          && host_name_opts='-s'
+  [[ ${HPC_OSs[@]} =~ $OS   ]] && host_name_opts='-A'
 
-if [[ $AT_TACC == yes ]]; then
-  [[ $TACC_SYS == frontera  ]] && filesystems=(/home1 /work)
-  [[ $TACC_SYS == ls6       ]] && filesystems=(/home1 /work)
-  [[ $TACC_SYS == vista     ]] && filesystems=(/home1 /work)
-  [[ $TACC_SYS == stampede3 ]] && filesystems=(/home1 /work)
-fi
+  host_name=`hostname $host_name_opts`
 
-OS=`uname`
-output=`df --version >/dev/null 2>&1`; status=$?
-if [[ $OS == Linux ]]; then
-  df_opts=-BG          # On Centos/Rocky
-elif [[ $OS == Darwin ]]; then
-  df_opts=-g           # On MacOS
-else
-  echo " ERROR (internal): Don't know OS for df command.  Bailing"
-  exit 1
-fi
-#TODO  Use new os-release check
+  LOCAL_fs=(/tmp)
 
-#Check use of local files systems
-local_disks=(/tmp)
-if [[ $OS == Darwin ]]; then                #Uses a single df for space and inode
-  echo "STORAGE QUOTAS"
-
-  for file_sys in ${local_disks[@]}; do
-    df_flds=(`df $df_opts $file_sys | tail -n 1`)
-  
-    space_used_no=${df_flds[4]%\%}
-    inode_used_no=${df_flds[7]%\%}
-  
-    [[ $((100-space_used_no)) -lt 11 ]] || [[ $((100-inode_used_no)) -lt 11 ]] &&
-    echo " WARNING: space or inode availability low on $file_sys" 
-  
-    printf " %-8s [SPACE: %4s%% available of %4sGB]  [INODES: %4s%% free (%7s)]\n" \
-         $file_sys $((100-space_used_no)) ${df_flds[1]} \
-                   $((100-inode_used_no)) ${df_flds[6]}
+# HPC_SITE File Systems
+  for sys in ls6 frontera stampede3 vista; do
+    [[ $host_name =~ $sys ]] && AT_TACC=yes TACC_SYS=$sys
   done
 
-elif [[ $OS == Linux ]]; then                       # requires executing 2 df's: space and inodes
-  echo "STORAGE QUOTAS"
-
-  for file_sys in ${local_disks[@]}; do
-    df_space_flds=(`df    $df_opts $file_sys | tail -n 1`)
-    df_inode_flds=(`df -i $df_opts $file_sys | tail -n 1`)
-  
-    space_used_no=${df_space_flds[4]%\%} 
-    inode_used_no=${df_inode_flds[4]%\%}
-  
-    [[ $((100-space_used_no)) -lt 11 ]] || [[ $((100-inode_used_no)) -lt 11 ]] &&
-    echo " WARNING: space or inode availability low on $file_sys" 
-  
-#   printf "%-8s [SPACE: %4s%% available of %4sGB]  [INODES: %4s%% free (%7s)]\n" \
-    printf " %-8s [SPACE: %4s%% available of %4s]  [INODES: %4s%% free (%7s)]\n" \
-           $file_sys $((100-space_used_no)) ${df_space_flds[1]} \
-                     $((100-inode_used_no)) ${df_inode_flds[1]}
-  done
-fi
-
-if [[ $AT_TACC == yes ]]; then
-
-  for fs in ${filesystems[@]}; do
-    do_cmd=lfs
-    [[ $fs =~ home1 ]] && [[ $TACC_SYS == vista     ]] && do_cmd=quota
-    [[ $fs =~ home1 ]] && [[ $TACC_SYS == stampede3 ]] && do_cmd=quota
-    [[ $fs =~ home1 ]] && [[ $TACC_SYS == ls6       ]] && do_cmd=quota
-
-    if [[ $do_cmd =~ lfs ]] ; then
-      common_out=(`lfs quota   -u $USER  $fs | sed -n '3p'`)
-      [[ ${common_out[4]} == "-" ]] && common_out[4]=0     #make grace 0 if "-"
-      [[ ${common_out[8]} == "-" ]] && common_out[8]=0
-
-      common_out[1]=`echo $(echo "scale=2; ${common_out[1]}/1048576"  | bc -l)` #kbytes to gbytes
-      common_out[2]=`echo $(echo "scale=2; ${common_out[2]}/1048576"  | bc -l)`
-      common_out[3]=`echo $(echo "scale=2; ${common_out[3]}/1048576"  | bc -l)`
-      percent_used_space=`echo $(echo "scale=2; 100*${common_out[1]}/${common_out[3]}"  | bc -l)`
-      percent_used_inode=`echo $(echo "scale=2; 100*${common_out[5]}/${common_out[7]}"  | bc -l)`
-
-      # Report at login:
-      # Disk         Usage (GB)     Limit    %Used   File Usage       Limit   %Used |
-      # /scratch         1657.0       0.0     0.00      7120972           0    0.00 |
-      #Vista $ lfs quota   -u $USER  /work | sed -n '3p'
-      #/work 450798756       0 1073741824       - 2999996       0 3000000       -
-
-      #first time write header
-      [[ ${filesystems[0]} == $fs ]] && \
-      echo " Disk         Usage (GB)     Limit    %Used   File Count      Limit  %Used "
-
-      printf  " %-13s %9s %9s %8s %12s %10s %6s\n" \
-               ${common_out[0]} \
-               ${common_out[1]} ${common_out[3]} $percent_used_space \
-               ${common_out[5]} ${common_out[7]} $percent_used_inode
+  HPC_fs=()
+  if [[ $AT_TACC == yes ]]; then
+    if [[ $TACC_SYS == frontera  ]]; then
+      HPC_fs=(/home1 /work)
+      cmds[0]="lfs quota -u $USER /home1 | sed -n '3p'"
+      cmds[1]="lfs quota -u $USER /work  | sed -n '3p'"
     fi
 
-    if [[ $do_cmd =~ quota ]] ; then
-      out=(`quota -w -f $fs | sed -n '3p'`)
+    if [[ $TACC_SYS == vista     ]] || 
+       [[ $TACC_SYS == ls6       ]] || 
+       [[ $TACC_SYS == stampede3 ]]; then
+         HPC_fs=(/home1 /work)
+         cmds[0]="    quota -w -f    /home1 | sed -n '3p'"
+         cmds[1]="lfs quota -u $USER /work  | sed -n '3p'"
+    fi
+  fi
+# end HPC_SITE File Systems
+  
 
-                  # filesys   used      quota     limit grace used      quota     limit grace
-      common_out=(${fs} ${out[1]} ${out[2]} ${out[3]} 0 ${out[4]} ${out[5]} ${out[6]} 0)
+  # Get maximum space needed for File System Name in header
+  ALL_fs=(${HPC_fs[@]} ${LOCAL_fs[@]})
+  NAME_sp=5  # Have at least 5 spaces
+  for name in ${ALL_fs[@]}; do
+    len=${#name}
+    [[ $len -gt $NAME_sp ]] && NAME_sp=$len
+  done
 
-      common_out[1]=`echo $(echo "scale=2; ${common_out[1]}/1048576"  | bc -l)` #kbytes to gbytes
-      common_out[2]=`echo $(echo "scale=2; ${common_out[2]}/1048576"  | bc -l)`
-      common_out[3]=`echo $(echo "scale=2; ${common_out[3]}/1048576"  | bc -l)`
-      percent_used_space=`echo $(echo "scale=2; 100*${common_out[1]}/${common_out[3]}"  | bc -l)`
-      if [[ ${common_out[7]} != 0 ]]; then  #fix for home1 on ls6
-        percent_used_inode=`echo $(echo "scale=2; 100*${common_out[5]}/${common_out[7]}"  | bc -l)`
+  # Print header
+  I_x='(M)'
+  [[ $O == V ]] || [[ $O == N ]]  &&
+    echo " FILESYSTEM QUOTAS: "   &&
+    printf " %-${NAME_sp}s  Usage(GB)  Limit(GB)  %%Used  -  Inodes%s  Limit%s  %%Used\n" \
+            "Disk" "$I_x" "$I_x"
+
+  OS=`uname`
+  [[ $OS == Linux  ]] && df_opts=-BG          # On Centos/Rocky
+  [[ $OS == Darwin ]] && df_opts=-g           # On MacOS
+  if [[ -z $df_opts ]]; then
+    echo " FS QUOTAS: ERROR (internal): Don't know OS for df command.  Bailing"
+    exit 1
+  fi
+  #TODO  Use new os-release check
+
+
+# CHECK LOCAL FILES SYSTEMS
+  if [[ $OS == Darwin ]]; then                #Uses a single df for space and inode
+   # $ df  /tmp            
+   # Filesystem   512-blocks      Used  Available Capacity iused      ifree %iused  Mounted on
+   # /dev/disk3s5 1942700360 315051688 1571387520    17% 1544861 7856937600    0%   /System/Volumes/Data
+  
+    for fs in ${LOCAL_fs[@]}; do
+      df_flds=(`df $df_opts $fs | tail -n 1`)
+    
+      space_used_no=${df_flds[4]%\%}
+      inode_used_no=${df_flds[7]%\%}
+
+   #Space
+    S_total=${df_flds[1]}
+    S_used=${df_flds[2]}
+    S_remain=${df_flds[3]}
+    PS_used=${df_flds[4]%\%}
+    PS_remain=$(bc <<< "100*$S_remain/$S_total")
+    [[ $PS_remain -lt 6 ]] && LS_warn+=($PS_remain) LS_warn_fs+=(${df_space_flds[5]})
+    [[ $PS_remain -lt 3 ]] && LS_fail+=($PS_remain) LS_fail_fs+=(${df_space_flds[5]})
+
+    #Inode info
+    I_used=${df_flds[5]} 
+    I_remain=${df_flds[6]} 
+    I_total=$(( I_used + I_remain ))
+    
+    PI_used=${df_flds[7]%\%} 
+    PI_remain=$(bc <<< "100*$I_remain/$I_total")
+    [[ $PI_remain -lt 6 ]] && LI_warn+=($PI_remain) LI_warn_fs+=(${df_space_flds[5]})
+    [[ $PI_remain -lt 3 ]] && LI_fail+=($PI_remain) LI_fail_fs+=(${df_space_flds[5]})
+    
+    I_remain=$(bc <<< "$I_remain/1000000")
+    I_used=$(  bc <<< "$I_used  /1000000")
+    I_total=$( bc <<< "$I_total /1000000")
+    
+   #  [[ $((100-space_used_no)) -lt 11 ]] || [[ $((100-inode_used_no)) -lt 11 ]] &&
+   #  echo " WARNING: space or inode availability low on $file_sys" 
+   #
+   #  printf " %-8s [SPACE: %4s%% available of %4sGB]  [INODES: %4s%% free (%7s)]\n" \
+   #       $file_sys $((100-space_used_no)) ${df_flds[1]} \
+   #                 $((100-inode_used_no)) ${df_flds[6]}
+
+    [[ $O == V ]] || [[ $O == N ]] &&
+      printf " %-${NAME_sp}s %6s     %6s     %6s     %6s    %6s    %6s\n" \
+              $fs \
+              ${S_used} ${S_total} ${PS_used} \
+              ${I_used} ${I_total} ${PI_used} 
+
+    [[ $O == T ]] && T_out+=("$fs ${PS_remain}% ")
+
+    done
+  
+  elif [[ $OS == Linux ]] && [[ ! -z $HPC_fs ]]; then  # requires executing df twice for space and inodes
+    for fs in ${LOCAL_fs[@]}; do
+      df_space_flds=(`df    $df_opts $fs | tail -n 1`)
+      df_inode_flds=(`df -i $df_opts $fs | tail -n 1`)
+    done
+  
+    #Space info
+    S_total=${df_space_flds[1]%\G}
+    S_used=${df_space_flds[2]%\G}
+    S_remain=${df_space_flds[3]%\G}
+    
+    PS_used=$(bc   <<< "100*$S_used/$S_total")
+    PS_remain=$(bc <<< "100*$S_remain/$S_total")
+    [[ $PS_remain -lt 6 ]] && [[ $PS_remain -ge 3 ]] && HPCS_warn+=($PS_remain) HPCS_warn_fs+=(${df_space_flds[5]})
+    [[ $PS_remain -lt 3 ]] &&                           HPCS_fail+=($PS_remain) HPCS_fail_fs+=(${df_space_flds[5]})
+    
+    #Inode info
+    I_total=${df_inode_flds[1]} 
+    I_used=${df_inode_flds[2]} 
+    I_remain=${df_inode_flds[3]} 
+    
+    PI_used=$(bc   <<< "100*$I_used/$I_total")
+    PI_remain=$(bc <<< "100*$I_remain/$I_total")
+    [[ $PI_remain -lt 6 ]] && [[ $PI_remain -ge 3 ]] && HPCI_warn+=($PI_remain) HPCI_warn_fs+=(${df_space_flds[5]})
+    [[ $PI_remain -lt 3 ]] &&                           HPCI_fail+=($PI_remain) HPCI_fail_fs+=(${df_space_flds[5]})
+    
+    I_remain=$(bc <<< "$I_remain/1000000")
+    I_used=$(  bc <<< "$I_used  /1000000")
+    I_total=$( bc <<< "$I_total /1000000")
+  
+    [[ $O == V ]] || [[ $O == N ]] &&
+      printf " %-${NAME_sp}s %6s     %6s     %6s     %6s    %6s    %6s\n" \
+              $fs \
+              ${S_used} ${S_total} ${PS_used} \
+              ${I_used} ${I_total} ${PI_used} 
+
+    [[ $O == T ]] && T_out+=("$fs ${PS_remain}% ")
+
+  fi
+
+  for i in ${!HPC_fs[@]}; do
+
+      fs=${HPC_fs[$i]}
+      out=(`eval ${cmds[$i]}`)
+
+      # stampede3$ quota -w -f /home1   ALSO: vista$ quota -w -f /home1 
+      # Disk ...
+      #      Filesystem        blocks   quota   limit   grace   files   quota   limit   grace
+      # ...:/stampede3/home1 14442436     0  14648436          198310     0    500000    
+      #               0         1         2      3       4        5       6       7       8
+      #               0         1         2      3                4       5       6 
+
+      # vista$ lfs quota -u milfeld /work 
+      # Disk quotas for usr milfeld (uid 1117):
+      # Filesystem  kbytes   quota   limit   grace   files   quota   limit   grace
+      #    /work 450798756       0 1073741824       - 2999996       0 3000000       -
+
+
+      common_out=(  ${out[@]})
+      if [[ ${#out[@]} == 7 ]]; then  # common_out assumes grace is a value (0 if not used)
+        common_out[5]=${out[4]}
+        common_out[6]=${out[5]}
+        common_out[7]=${out[6]}
+        common_out[8]=0 common_out[4]=0
       else
-        percent_used_inode="-"
-        common_out[7]="-"
+        [[ ${common_out[4]} == "-" ]] && common_out[4]=0     #make grace 0 if "-"
+        [[ ${common_out[8]} == "-" ]] && common_out[8]=0
       fi
 
-      echo " Disk         Usage (GB)     Limit    %Used   File Count      Limit  %Used "
-      printf  " %-13s %9s %9s %8s %12s %10s %6s\n" \
-               ${common_out[0]} \
-               ${common_out[1]} ${common_out[3]} $percent_used_space \
-               ${common_out[5]} ${common_out[7]} $percent_used_inode
-    fi
+      #Space info  KB->GB
+      S_total=$(bc <<< "${common_out[3]}/1048576")
+      S_used=$( bc <<< "${common_out[1]}/1048576")
+      S_remain=$(( S_total - S_used ))
+
+      PS_used=$(bc   <<< "100*$S_used/$S_total")
+      PS_remain=$(bc <<< "100*$S_remain/$S_total")
+      [[ $PS_remain -lt 6 ]] && [[ $PS_remain -ge 3 ]] && HPCS_warn+=($PS_remain) HPCS_warn_fs+=($fs)
+      [[ $PS_remain -lt 3 ]] &&                           HPCS_fail+=($PS_remain) HPCS_fail_fs+=($fs)
+  
+      #Inode info
+      I_remain=$(( ${common_out[7]} - ${common_out[5]} ))
+      I_total=$(  bc <<< "scale=2; ${common_out[7]}/1000000")
+      I_used=$(   bc <<< "scale=2; ${common_out[5]}/1000000")
+      I_remain=$( bc <<< "scale=2; $I_remain/1000000")
+  
+      PI_used=$(bc   <<< "100*$I_used/$I_total")
+      PI_remain=$(bc <<< "100*$I_remain/$I_total")
+      [[ $PI_remain -lt 6 ]] &&  [[ $PI_remain -ge 3 ]] && HPCI_warn+=($PI_remain) HPCI_warn_fs+=($fs)
+      [[ $PI_remain -lt 3 ]] &&                            HPCI_fail+=($PI_remain) HPCI_fail_fs+=($fs)
+
+      [[ $O == N ]] || [[ $O == V ]] &&
+      printf " %-${NAME_sp}s %6s     %6s     %6s     %6s    %6s    %6s\n" \
+              $fs \
+              ${S_used} ${S_total} ${PS_used} \
+              ${I_used} ${I_total} ${PI_used}
+
+      [[ $O == T ]] && T_out+=("$fs ${PS_remain}% ")
+
   done
-fi
-#Disk quotas for user milfeld (uid 1117): 
-#     Filesystem  blocks   quota   limit   grace   files   quota   limit   grace
-#192.168.16.21:/vista/home1 23126004       0 24414060          282610       0  500000        
-#Disk quotas for usr milfeld (uid 1117):
-#     Filesystem  kbytes   quota   limit   grace   files   quota   limit   grace
-#          /work 450798756       0 1073741824       - 2999996       0 3000000       -
-#
-
-# df INFO from LINUS
-#$ df  -BG /tmp   #vistat
-#Filesystem                  1G-blocks  Used Available Use% Mounted on
-#/dev/mapper/rootvg01-lv_tmp      286G    3G      283G   1% /tmp
-#$  df -i -BG /tmp
-#Filesystem                     Inodes IUsed     IFree IUse% Mounted on
-#/dev/mapper/rootvg01-lv_tmp 149704704 13790 149690914    1% /tmp
-
-#exit 0
 
 
-#  space_used_MB=${limits[0]}
-# space_limit_MB=${limits[2]}
-#  inode_used=${limits[3]}
-# inode_limit=${limits[5]}
-# 
-# if [[ $space_limit_MB -gt 0.00 ]]; then
-#   if [[ $space_used_MB/$space_limit_MB -gt 0.95 ]]; then
-#     echo " Space used in $FS is above 95%."
-#   else
-#     echo "  ${percent}% of $percent of  12345 MB in $FS (limit: $ 
-#     #   At 90% of $FS quota (17GB used, 240GB available)
-#     #   At 90% of $FS user quota (17/240 GB used/avail)
-#   fi
-# else
-#   echo " No space limit on $FS."
-#   exit 0
-# fi
+# Print Check Info
 
-     
-# v====== TACC COMMENTS ======v
+  [[ $O == T ]] &&
+    echo "FILESYSTEM QUOTAS: (${T_out[@]}  %remaining)"
 
-# Vista $ quota -f /scratch
-#Disk quotas for user milfeld (uid 1117): 
-#     Filesystem  blocks   quota   limit   grace   files   quota   limit   grace
-#192.168.16.21:/vista/scratch
-#                1737490432       0 9765624217600         7120972       0       0   
+  #WARN
+  if [[ ${#LS_warn[@]} -ne 0 ]]; then
+    STATUS=3
+    for i in ${!LS_warn[@]}; do
+      echo " WARNING:  ${LS_warn_fs[$i]} has only ${LS_warn[$i]}% storage available."  
+    done
+  fi
 
-#Vistat $ quota -f /home1
-#Disk quotas for user milfeld (uid 1117): 
-#    Filesystem  blocks   quota   limit   grace   files   quota   limit   grace
-#192.168.16.21:/vista/home1
-#                23125632       0 24414060          282526       0  500000     
+  if [[ ${#LI_warn[@]} -ne 0 ]]; then
+    STATUS=3
+    for i in ${!LI_warn[@]}; do
+      echo " WARNING :  ${LI_warn_fs[$i]} has only ${LI_warn[$i]}% remaining inodes."  
+    done
+  fi
 
-# Vistat Login Disk information
-#------------------------ Disk quotas for user milfeld -------------------------
-#| Disk         Usage (GB)     Limit    %Used   File Usage       Limit   %Used |
-#| /scratch         1657.0       0.0     0.00      7120972           0    0.00 |
-#| /home1*            22.1      23.3    94.72       282526      500000   56.51 |
-#| /work*            429.9    1024.0    41.98      2999996     3000000  100.00 |
-#-------------------------------------------------------------------------------
+  if [[ ${#HPCS_warn[@]} -ne 0 ]]; then
+    STATUS=3
+    for i in ${!HPCS_warn[@]}; do
+      echo " WARNING :  ${HPCS_warn_fs[$i]} has only ${HPCS_warn[$i]}% storage available."  
+    done
+  fi
+
+  if [[ ${#HPCI_warn[@]} -ne 0 ]]; then
+    STATUS=3
+    for i in ${!HPCI_warn[@]}; do
+      echo " WARNING :  ${HPCI_warn_fs[$i]} has only ${HPCI_warn[$i]}% remaining inodes."  
+    done
+  fi
+
+  #FAIL
+  if [[ ${#LS_fail[@]} -ne 0 ]]; then
+    STATUS=1
+    for i in ${!LS_fail[@]}; do
+      echo " WARNING :  ${LS_fail_fs[$i]} has only ${LS_fail[$i]}% storage available."  
+    done
+  fi  
+
+  if [[ ${#LI_fail[@]} -ne 0 ]]; then
+    STATUS=1
+    for i in ${!LI_fail[@]}; do
+      echo " CRITICAL:  ${LI_fail_fs[$i]} has only ${LI_fail[$i]}% remaining inodes."  
+    done
+  fi  
+
+  if [[ ${#HPCS_fail[@]} -ne 0 ]]; then
+    STATUS=1
+    for i in ${!HPCS_fail[@]}; do
+      echo " CRITICAL:  ${HPCS_fail_fs[$i]} has only ${HPCS_fail[$i]}% storage available."  
+    done
+  fi  
+
+  if [[ ${#HPCI_fail[@]} -ne 0 ]]; then
+    STATUS=1
+    for i in ${!HPCI_fail[@]}; do
+      echo " CRITICAL:  ${HPCI_fail_fs[$i]} has only ${HPCI_fail[$i]}% remaining inodes."  
+    done
+  fi  
+
+  exit $STATUS
diff --git a/06_Allocations b/06_Allocations
--- a/06_Allocations
+++ b/06_Allocations
@@ -1,10 +1,16 @@
 #!/bin/bash
 
-[[ $# != 1 ]] && O=N    #Command line options T=terse,v=Verbose, default Normal
-[[ $1 == t ]] && O=T 
-[[ $1 == v ]] && O=V 
 
-STATUS=0
+#TODO  warning isi project ending soon or near 5% limit
+##TODO fail is 2 percent left
+
+  [[ $# == 0 ]] && O=N    #Command line options T=terse,v=Verbose, default Normal
+  [[ $1 =~ t ]] && O=T
+  [[ $1 =~ v ]] && O=V
+  [[ ! "$O" =~ [NTV] ]] && echo "USAGE: $0 [-t|-v] # terse|verbose output"
+
+  STATUS=0
+
   HPC_OSs=(rocky centos fedora ubuntu debian)
   if [[ -f /etc/os-release ]]; then
     output=$( grep ^ID= /etc/os-release ) #e.g. ID="rocky"
@@ -24,21 +30,21 @@ STATUS=0
 
   host_name=`hostname $opts`
 
-for sys in frontera vista stampede ls6; do
-  [[ $host_name =~ $sys ]] && AT_TACC=yes TACC_SYS=$sys
-done
+  for sys in frontera vista stampede ls6; do
+    [[ $host_name =~ $sys ]] && AT_TACC=yes TACC_SYS=$sys
+  done
 
-[[ $AT_TACC != yes ]] && echo " ALLOCATIONS" && echo " NONE programmed for this systems." && exit 0
+  [[ $AT_TACC != yes ]] && echo " ALLOCATIONS" && echo " NONE programmed for this systems." && exit 0
 
                   #milfeld:*:1117:825112:milfeld:/home1/00770/milfeld:/bin/bash
-user_info=`getent passwd $USER`
-IFS=":" read -ra usr_etc_pwd <<< "$user_info"  # put fields in /usr_etc_pwd array
+  user_info=`getent passwd $USER`
+  IFS=":" read -ra usr_etc_pwd <<< "$user_info"  # put fields in /usr_etc_pwd array
 
-user=${usr_etc_pwd[0]}
- uid=${usr_etc_pwd[2]}
- gid=${usr_etc_pwd[3]}
-home=${usr_etc_pwd[5]}
-login_shell=${usr_etc_pwd[6]}
+  user=${usr_etc_pwd[0]}
+   uid=${usr_etc_pwd[2]}
+   gid=${usr_etc_pwd[3]}
+  home=${usr_etc_pwd[5]}
+  login_shell=${usr_etc_pwd[6]}
 
 if [[ $AT_TACC == yes ]]; then
   TACC_ACC_DIR="/usr/local/etc/"
@@ -52,17 +58,15 @@ if [[ $AT_TACC == yes ]]; then
   status=$?
   projects=("${projects[@]:1}")  #remove 1st element, user name
   if [[ $status == 0 ]]; then
-    if [[ $O == N ]] || [[ $O == V ]] ; then
-      echo "PROJECTS found (IDs ${projects[@]}, repectively): "
-    fi
-    if [[ $O == T ]] ; then
-      echo "PROJECTS of user $USER."
+    if [[ $O == V ]] ; then
+      echo " PROJECTS found (IDs ${projects[@]}, repectively): "
     fi
   else
-    echo "No Projects found for user $user."
+    echo " PROJECTS: NO PROJECTS FOUND."
     exit 1
   fi
 
+# Project Details
   valid_count=0 expired_count=0
   for proj_id in ${projects[@]}; do
     name_id=( $(grep -E " $proj_id\\b" $proj_map) )  #$proj_map
@@ -90,33 +94,51 @@ if [[ $AT_TACC == yes ]]; then
 
       if [[ $today_no -gt $end_no ]]; then
         expired_count=$(( expired_count + 1 ))
-        if [[ $O == N ]] || [[ $O == V ]] ; then
-          echo -e "  EXPIRED: Project $proj_name has expired ($end_date)\n"
+        if [[ $O == V ]] ; then
+          echo "  EXPIRED: $proj_name expired $end_date"
         fi
         exp_proj+=($proj_name)
+        EXP_proj_date+=("$proj_name $end_date ")
       else
-        if [[ $O == N ]] || [[ $O == V ]] ; then
+        if [[ $O == V ]] ; then
           printf  " ACTIVE : %8s (SUs Alloc:Used:Bal:Exp) %8s %8.0f %8.0f %s \n" \
                   "$proj_name" "${allocate}" "${used}" "${balance}" "$end_date"
         fi
+          PC_remain=$(bc   <<< "100*$balance/$allocate")
           balance=${balance%.*}
           act_proj+=( $proj_name:Bal=$balance)
+          ACT_proj+=( $proj_name )
+          ACT_proj_PCremain+=( "$proj_name ${PC_remain}% " )
+          ACT_proj_bal_PCremain+=( "$proj_name $balance ${PC_remain}%" )
+      fi
+#exp_proj=(CCSC1234 abc1234)   #For testing
+#EXP_proj_date=("CCSC1234 10/10/24"  "abc1234 9/9/23")
+      if [[ $proj_id == ${projects[-1]} ]] && [[ $O == T ]] ; then   #las proj_id
+         [[ ${#exp_proj[@]} -gt 0 ]] && EXP="Expired: (${exp_proj[@]})"
+         [[ ${#act_proj[@]} -gt 0 ]] && ACT="(${ACT_proj_PCremain[@]} %remain)"
+         [[ $valid_count    -gt 0 ]] &&
+           echo " PROJECTS: $ACT $EXP" 
+      fi
+      if [[ $proj_id == ${projects[-1]} ]] && [[ $O == N ]] ; then   #las proj_id
+        #[[ ${#exp_proj[@]} -gt 0 ]] && EXP="Expired: (${exp_proj[@]})"
+         [[ ${#act_proj[@]} -gt 0 ]] || [[ ${#exp_proj[@]} -gt 0 ]] &&
+         echo " PROJECTS: Active/Inactive  Balance(SUs), %Available"
+         [[ ${#act_proj[@]} -gt 0 ]] &&
+         echo " ACTIVE: ${ACT_proj_bal_PCremain[@]}"
+         [[ ${#exp_proj[@]} -gt 0 ]] &&
+         echo " EXPIRED: ${EXP_proj_date[@]}"
       fi
 
-      if [[ $proj_id == ${projects[-1]} ]] && [[ $O == T ]] ; then
-    # if [[ $O == T ]] ; then
-         [[ ${#exp_proj[@]} -gt 0 ]] && EXP="Expired: ${exp_proj[@]}"
-         echo " Active: ${act_proj[@]} $EXP" 
-      fi
     fi
   done
 
+  # FAIL if no accounts valable, WARN if some inactive/expired
   if [[ $valid_count -gt 0 ]]; then 
     if [[ $expired_count -eq $valid_count ]]; then
       echo -e " FAIL: All valid projects are expired.\n"   #FAILURE
       exit 1
     fi
-    [[ $expired_count -gt 0 ]] && exit 3                    #WARNING
+    [[ $expired_count -gt 0 ]] && exit 3                   #WARNING
   fi
 
   exit 0
diff --git a/07_Batch b/07_Batch
--- a/07_Batch
+++ b/07_Batch
@@ -4,9 +4,10 @@
 # determine what the scheduler
 # show queues, and determine status  (si with status)
 
-[[ $# != 1 ]] && O=N    #Command line options T=terse,v=Verbose, default Normal
-[[ $1 == t ]] && O=T 
-[[ $1 == v ]] && O=V 
+  [[ $# == 0 ]] && O=N    #Command line options T=terse,v=Verbose, default Normal
+  [[ $1 =~ t ]] && O=T 
+  [[ $1 =~ v ]] && O=V 
+  [[ ! "$O" =~ [NTV] ]] && echo "USAGE: $0 [-t|-v] # terse|verbose output"
 
 STATUS=0
 
@@ -19,14 +20,21 @@ type bsub >& /dev/null
 type llsubmit >& /dev/null
 [[ $? == 0 ]] && batch_sched+=(LOADLEVELER   ) && sched_cmds=(llsubmit llcancel llq)
 
+if [[ ${#batch_sched[@]} -gt 1 ]]; then
+   echo " BATCH: System error found multiple managers (${batch_sched[@]})"
+   exit 1
+fi
+
 #batch_sched=()
 if [[ ${#batch_sched[@]} == 0 ]]; then
-   echo "No BATCH MANAGER FOUND. Checked for: "
+   echo " BATCH: No BATCH MANAGER FOUND. Checked for: "
    echo " Checked for SLURM,  PBS_TORQUE_SGE, LSF  and LOADLEVER with commands:"
    echo "             sbatch, qsub,           bsub,    llsubmit, respectively."
    exit 1
 elif [[ ${#batch_sched[@]} == 1 ]]; then
-   echo "BATCH manager is ${batch_sched[0]}"
+   BATCH_man=${batch_sched[@]}
+   [[ $O == V ]] &&
+     echo " BATCH:  Batch Manager is ${batch_sched[0]}"
 fi
 
 #host_name=`hostname -A`
@@ -51,34 +59,57 @@ for sched_cmd in ${sched_cmds[@]}; do
 done
 
 if [[ ${#sched_cmds[@]} -eq ${#found_cmds[@]} ]]; then
-   echo " All BATCH scheduler command(s) found: ${found_cmds[@]}"
+   
+   [[ $O == V ]] &&
+     echo " All BATCH scheduler command(s) found: ${found_cmds[@]}"
+   [[ $O == N ]] &&
+     echo " BATCH:  All ${batch_sched[0]} cmds found: ${found_cmds[@]}."
 else
    echo " Only found BATCH scheduler command(s): ${found_cmds[@]}"
    echo " Could not find the BATCH command(s): ${not_found_cmds[@]}"
    exit 1
 fi
 
+if [[ ${batch_sched[@]} == SLURM ]]; then
 
-#q_status=(`sinfo --noheader -o "%20P %5a"`)
-q_status=`sinfo --noheader -o "   %10P %5a"`
-queue_count=`sinfo --noheader -o "   %10P %5a" | wc -l`
-up_count=`echo $q_status | grep -o '\bup\b' | wc -l`
-
-[[ $up_count == 0 ]]             && echo " NO QUEUES ARE UP"  && exit 1
-[[ $queue_count -ne $up_count ]] && STATUS=3
-
-if [[ $O == N  ]] || [[ $O == V ]]; then
-  echo " PARTITION  AVAILABILITY" &&
-  echo "$q_status"
-fi
-
-[[ $queue_count -eq $up_count ]] && echo " All Queues are UP." 
-
-if [[ $O == T  ]]; then
-  if [[ $queue_count -ne $up_count ]]; then
-    part_status=$(sinfo --noheader -o "(%P: %a)" | grep -v '\bup\b')
-    echo " NOT ALL QUEUES ARE up. List: " $part_status && STATUS=3
+  #q_status=(`sinfo --noheader -o "%20P %5a"`)
+     q_status=`sinfo --noheader -o "   %10P %5a"`
+  queue_count=`sinfo --noheader -o "   %10P %5a" | wc -l`
+     up_count=`echo $q_status | grep -o '\bup\b' | wc -l`
+  
+  [[ $up_count == 0 ]]             && echo " BATCH: NO QUEUES ARE UP"  && exit 1
+  [[ $queue_count -ne $up_count ]] && STATUS=1
+  
+  if [[ $O == V ]]; then
+    echo " PARTITION  AVAILABILITY" &&
+    echo "$q_status"
   fi
+  
+  if [[ $queue_count -eq $up_count ]]; then 
+    [[ $O == V ]] && echo " All Queues are UP." 
+  fi
+
+    not_up_status=$(sinfo --noheader -o "(%P: %a)" | grep -v '\bup\b')
+         up_status=$(sinfo --noheader -o "(%P: %a)" | grep    '\bup\b')
+  
+    if [[ $O == N  ]]; then
+          up=( $(sinfo --noheader -o "%P %a" | grep    '\b\up\b' | sed 's/up//') )
+      not_up=( $(sinfo --noheader -o "%P %a" | grep -v '\b\up\b' | sed 's/up//') )
+      [[ ${#up[@]}     -gt 0 ]] && echo " Queues   UP: ${up[@]}"
+      [[ ${#not_up[@]} -gt 0 ]] && echo " Queues DOWN: ${not_up[@]}"
+    fi
+
+    if [[ $queue_count -eq $up_count ]]; then
+      [[ $O == T  ]] &&
+        echo " QUEUES: ALL UP."
+    else
+      if [[ $O == T  ]]; then
+        not_up_status=$(sinfo --noheader -o "(%P: %a)" | grep -v '\bup\b')
+        echo " QUEUES: DOWNED  $not_up_status"
+      fi
+      STATUS=3
+    fi
+
 fi
 
 exit $STATUS
diff --git a/09_BlockedUsers b/09_BlockedUsers
--- a/09_BlockedUsers
+++ b/09_BlockedUsers
@@ -1,17 +1,18 @@
 #!/bin/bash
 
 # @TACC searches tacc_filter_options for blocked $USER.
-# If found print failure, and message if it exists.
-# See example of blocked_user line and message.
+# If found exit with failure (exit 1), and message if it exists.
+# See example of blocked_user line and message (at end).
 # non-TACC sites need to interact with their ACL mechanism.
 # Based on Sanitytool's sanitycheck. Written and revised. 
 #                                   2025-08-01 Kent Milfeld
 
-#TODO Search for message within range of queue_acls/public
+##TODO Search for message within range of queue_acls/public
 
-[[ $# != 1 ]] && O=N    #Command line options T=terse,v=Verbose, default Normal
-[[ $1 == t ]] && O=T 
-[[ $1 == v ]] && O=V 
+  [[ $# == 0 ]] && O=N    #Command line options T=terse,v=Verbose, default Normal
+  [[ $1 =~ t ]] && O=T 
+  [[ $1 =~ v ]] && O=V 
+  [[ ! "$O" =~ [NTV] ]] && echo "USAGE: $0 [-t|-v] # terse|verbose output"
 
 STATUS=0
 
@@ -36,8 +37,8 @@ STATUS=0
   for sys in frontera vista stampede ls6; do
     [[ $host_name =~ $sys ]] && AT_TACC=yes TACC_SYS=$sys
   done
-  [[ $AT_TACC != yes ]] && echo " RESERVATIONS" &&  
-     echo " Checklist not configured for Reservations on this system." && exit 0
+  [[ $AT_TACC != yes ]] && 
+     echo " QUEUE ACCESS: System is not configured to block queue access." && exit 0
 
 if [[ $AT_TACC == yes ]]; then
   ACL_DIR=/etc/slurm
@@ -73,15 +74,19 @@ if [[ $AT_TACC == yes ]]; then
 
     else
       [[ $O == T ]] &&
-        echo "BLOCKED QUEUE ACCESS"  &&
-        echo " User $USER has access to all queues."
-      [[ $O == N ]] || [[ $O == V ]] &&
-        echo "BLOCKED QUEUE ACCESS"  &&
-        echo " $USER has access to all queues (searched $filter_path)."
+        echo " QUEUE ACCESS:  No Restrictions."
+      [[ $O == N ]] &&
+        echo " QUEUE ACCESS: Checking block-user filter." &&
+        echo " $USER has access to all queues."
+      [[ $O == V ]] &&
+        echo " QUEUE ACCESS: Checking block-user filter ($filter_path)." &&
+        echo " $USER has access to all queues."
+
     fi 
   else
-    echo " NO \"ALL =\" line found in public queue acl file."
-    echo " Even if no user found, root is usually blocked."
+    echo " QUEUE ACCESS: NO \"ALL =\" line found in public queue ACL file."
+    echo " (The should be present and have at least \"root\" included."
+    echo " Please submit a ticket to TACC help with this report, thanks!"
     echo " If job submission works, don't consider this a problem."
     STATUS=3
   fi
