Now works with Darwin (macos).

diff --git a/01_SSH b/01_SSH
--- a/01_SSH
+++ b/01_SSH
@@ -14,56 +14,107 @@
   [[ $1 == t ]] && O=T
   [[ $1 == v ]] && O=V
 
-STATUS=0
+  STATUS=0
 
-i=0
-pub_key_files=( id_ed25519.pub id_rsa.pub )
+  HPC_OSs=(rocky centos fedora ubuntu debian)
+
+   SSH_DIR=$HOME/.ssh
+   pub_key_files=( id_ed25519.pub id_rsa.pub id_ecdsa.pub )
+  priv_key_files=( id_ed25519     id_rsa     id_ecdsa )
+
+
+  ##NEW
+  filenames=( .ssh         pub_key        priv_key        authorized_keys )
+   perms=(    drwx------   -rw-r--r--     -rw-------      -rw------- )
+  set_perms=( 700          644            600             600 )
+  functions=( directory    "public key"   "private key"   authorized_keys )
+
+  if [[ -f /etc/os-release ]]; then
+    output=$( grep ^ID= /etc/os-release ) #e.g. ID="rocky"
+    eval $output
+    OS=$ID
+    if [[ ! $HPC_OSs =~ $OS ]]; then
+       echo " internal ERROR: could not get OS from /etc/os-release"
+       echo "   search list ( ${HPC_OSs[@]} )"
+       exit 1
+    fi
+  else
+    [[ `uname -a` =~ Darwin ]] && OS=darwin
+  fi
 
 echo "SSH setup"
 
-output=`ls $HOME/.ssh/*.pub`
+# SSH Directory
+if [[ ! -d $SSH_DIR ]]; then  # Does $HOME/.ssh exist
+   unfound=(${filenames[0]})
+   echo " NO \$HOME/.ssh directory found." && exit 1
+else
+  found=(${filenames[0]})
+  [[ $O == N ]] || [[ $O == V ]] &&
+  echo " Found ${functions[0]} ${filenames[1]}."
+  
+fi
+
+# PUBLIC KEY file(s)
+output=`ls $SSH_DIR/*.pub 2>/dev/null`  #pub key
 if [[ $? != 0 ]]; then
-  echo " Could not find any public key (of form \*pub)."
-  exit 1
+  echo " NO ${functions[1]} Found (of form \*pub)."
+  STATUS=1
 else   #determine key type
   for file in ${pub_key_files[@]}; do
-    if [[ $output =~ $file  ]]; then
-       pub_keys+=($file)
-    fi
+    [[ $output =~ $file  ]] && pub_keys+=($file)
   done
 fi
- if [[ ${#pub_keys[@]}  == 1 ]]; then
-   if [[ $O == N ]] || [[ $O == V ]]; then
-    echo " Found public  key ${pub_keys[0]}" && pub_key=${pub_keys[0]}
-   fi
-   [[ $O == T ]]  && T_string="Found public key ${pub_keys[0]}"
- fi
- [[ ${#pub_keys[@]}  == 0 ]] && echo " Found NO public key (searched: ${pub_key_files[@]})" && exit 1
-#[[ ${#pub_keys[@]} -gt 1 ]] && echo " Found Multiple public key ${pub_keys[@]}." && exit 1
 
- pub_key=${pub_keys[0]}
-priv_key=${pub_key%%.pub}
+if [[ ${#pub_keys[@]}  == 1 ]]; then
+  filenames[1]=${pub_keys[0]}
+  found+=(${filenames[1]})
 
-output=`ls $HOME/.ssh/$priv_key`
-if [[ $? == 0 ]]; then
-   [[ $O == N ]] || [[ $O == V ]] && 
-     echo " Found private key $priv_key"
-   [[ $O == T ]] && 
-     T_string="$T_string and private key $priv_key" 
-else
-  echo " Could NOT find private key $priv_key."; exit 1
+  [[ $O == N ]] || [[ $O == V ]] &&
+    echo " Found ${functions[1]} ${filenames[1]}" && pub_key=${pub_keys[0]}
+fi
+if [[ ${#pub_keys[@]} == 0 ]]; then
+  unfound+=(${filenames[1]})
+  skip=(1)
+  echo " NO ${functions[1]} Found (searched: ${pub_key_files[@]})" && STATUS=1
 fi
 
-filenames=( .ssh $priv_key $pub_key authorized_keys )
-pathnames=( $HOME/.ssh $HOME/.ssh/$priv_key $HOME/.ssh/$pub_key $HOME/.ssh/authorized_keys )
- perms=(     drwx------ -rw-------           -rw-r--r--          -rw------- )
-#perms=(     .rwx------ .rw-------           .rw-r--r--          .rw------- ) #tests
-set_perms=( 700        600                  644                 600 )
- #echo ${pathnames[@]}
- #echo ${perms[@]}
- #echo ${set_perms[@]}
- #echo ==================================================
+# PRIVATE KEY file(s)
+for file in ${priv_key_files[@]}; do
+  output=`ls $SSH_DIR/$file 2>/dev/null`  #priv key
+  [[ $? == 0 ]] && priv_keys+=($file)
+done
 
+if [[ ${#priv_keys[@]}  == 1 ]]; then
+  filenames[2]=${priv_keys[0]}
+  found+=(${filenames[2]})
+
+  [[ $O == N ]] || [[ $O == V ]] &&
+    echo " Found ${functions[2]} ${filenames[2]}" && priv_key=${priv_keys[0]}
+fi
+if [[ ${#priv_keys[@]} == 0 ]]; then
+  unfound+=(${filenames[2]})
+  skip+=(2)
+  echo " NO ${functions[2]} Found (searched: ${priv_key_files[@]})" && STATUS=1
+fi
+
+# AUTHORIZED_KEYS file
+output=`ls $SSH_DIR/${filenames[3]} 2>/dev/null`  #authorized_keys
+if [[ $? != 0 ]]; then
+  unfound+=(${filenames[3]})
+  skip+=(3)
+  echo " NO ${functions[3]} file Found."
+  STATUS=1
+else
+  found+=(${filenames[3]})
+fi
+
+if [[ $O == T ]]; then
+  flat_found="${found[@]}" flat_unfound="${unfound[@]}"
+  printf  " SSH Found files :    (%s)\n" "$flat_found"
+  [[ ${#unfound[@]} -gt 0 ]] &&
+  printf " SSH NOT Found files: (%s)\n" "$flat_unfound"
+fi
 
 check_perm(){
 
@@ -74,12 +125,14 @@ check_perm(){
   local O=$4
   return_status=0
 
-  stat_perm=`stat -c %A ${pathnames[$i]}`
+  opts='-c %A'
+  [[ $OS == darwin ]]          && opts='-f %Sp'
+  [[ ${HPC_OSs[@]} =~ $OS   ]] && opts='-c %A'
+  stat_perm=`stat $opts ${pathname}`
   status=$?
   
-  name=`basename ${pathnames[$i]}`
-  short_pathname=$(echo ${pathnames[$i]} | sed 's@'$HOME'@$HOME@')
- #echo short_pathname=$short_pathname
+  name=`basename ${pathname}`
+  short_pathname=$(echo ${pathname} | sed 's@'$HOME'@$HOME@')
   
   
   if [[ $stat_perm == ${perms[$i]} ]]; then
@@ -95,9 +148,15 @@ check_perm(){
 
 }
 
-for i in ${!pathnames[@]}; do
-   check_perm ${pathnames[$i]} ${perms[$i]} ${set_perms[$i]} $O
-   [[ $return_status != 0 ]] && STATUS=$return_status
+for i in ${!filenames[@]}; do
+  if [[ ! "${skip[@]}" =~ $i ]]; then
+    path_name=$SSH_DIR/${filenames[$i]}
+    [[ $i == 0 ]] &&  path_name=$SSH_DIR  #Special, the Directory
+
+    check_perm ${path_name} ${perms[$i]} ${set_perms[$i]} $O
+
+    [[ $return_status != 0 ]] && STATUS=$return_status
+  fi
 done
 
 if [[ $O == T ]] && [[ $STATUS == 0 ]]; then
diff --git a/02_Storage b/02_Storage
--- a/02_Storage
+++ b/02_Storage
@@ -1,4 +1,4 @@
-#!/usr/bin/bash
+#!/bin/bash
 
 # 1.) Determine if USER STORAGE DIRS (US_DIRS) are defined
 #     HOME, WORK, SCRATCH are critical, not defined is failure
@@ -14,17 +14,42 @@
 [[ $1 == t ]] && O=T
 [[ $1 == v ]] && O=V
 
+HPC_OSs=(rocky centos fedora ubuntu debian)
+  if [[ -f /etc/os-release ]]; then
+    output=$( grep ^ID= /etc/os-release ) #e.g. ID="rocky"
+    eval $output
+    OS=$ID
+    if [[ ! $HPC_OSs =~ $OS ]]; then
+       echo " internal ERROR: could not get OS from /etc/os-release"
+       echo "   search list ( ${HPC_OSs[@]} )"
+       exit 1
+    fi
+  else
+    [[ `uname -a` =~ Darwin ]] && OS=darwin
+  fi
+
+
 STATUS=0
 
-host_name=`hostname -A`
+
+[[ $OS == darwin ]]          && opts='-s'
+[[ ${HPC_OSs[@]} =~ $OS   ]] && opts='-A'
+host_name=`hostname $opts`
 for sys in frontera vista stampede ls6; do
   [[ $host_name =~ $sys ]] && AT_TACC=yes TACC_SYS=$sys
 done
-
 if [[ $AT_TACC == yes ]]; then
    USER_STORAGE_DIRS=( HOME  SCRATCH WORK  STOCKYARD )
   USER_STORAGE_PERMS=( drwx  drwx    drwx  drwx     )
   CRITICAL_STORAGE_DIRS=( HOME )
+fi
+if [[ $OS == darwin ]]; then
+      USER_STORAGE_DIRS=( HOME )
+     USER_STORAGE_PERMS=( drwx )
+  CRITICAL_STORAGE_DIRS=( HOME )
+fi
+
+if [[ $AT_TACC == yes ]] || [[ $OS == darwin ]]; then
 
  #echo "STORAGE Environment Variable Definition & Directory Perms." 
   echo "STORAGE ENV VARS & PERMS"
@@ -62,11 +87,14 @@ if [[ $AT_TACC == yes ]]; then
     STATUS=1  #redundant, JIC some directories become only warnings in future
   fi
 
+  [[ $OS == darwin ]]          && opts='-f %Sp'
+  [[ ${HPC_OSs[@]} =~ $OS   ]] && opts='-c %A'
+
   # Check USER permission of directories for which variables are defined.
   if [[ ${#found_storage_dirs[@]} -gt 0 ]]; then
     for i in ${!found_storage_dirs[@]}; do
        user_dir=${found_storage_dirs[$i]}
-       stat_perm=`stat -c %A ${found_pathnames[$i]}`
+       stat_perm=`stat $opts ${found_pathnames[$i]}`
        status=$? 
        if [[ $stat_perm =~ ^${found_storage_perms[$i]} ]]; then
           [[ $O == N ]] || [[ $O == V ]] &&
diff --git a/05_Compilers b/05_Compilers
--- a/05_Compilers
+++ b/05_Compilers
@@ -13,28 +13,64 @@
 [[ $1 == t ]] && O=T 
 [[ $1 == v ]] && O=V 
 
+HPC_OSs=(rocky centos fedora ubuntu debian)
+  if [[ -f /etc/os-release ]]; then
+    output=$( grep ^ID= /etc/os-release ) #e.g. ID="rocky"
+    eval $output
+    OS=$ID
+    if [[ ! $HPC_OSs =~ $OS ]]; then
+       echo " internal ERROR: could not get OS from /etc/os-release"
+       echo "   search list ( ${HPC_OSs[@]} )"
+       exit 1
+    fi
+  else
+    [[ `uname -a` =~ Darwin ]] && OS=darwin
+  fi
+
 STATUS=0
 
-host_name=`hostname -A`
+[[ $OS == darwin ]]          && opts='-s'
+[[ ${HPC_OSs[@]} =~ $OS   ]] && opts='-A'
+
+host_name=`hostname $opts`
 for sys in frontera vista stampede ls6; do
   [[ $host_name =~ $sys ]] && AT_TACC=yes TACC_SYS=$sys
 done
 
+module_clause=""
+output=`type module 2>/dev/null`
+[[ $? == 0 ]] && module_clause="in present module environment"
+
 compiler_families=(nvidia intel oneAPI llvm gcc)
 
-declare -A sets
-sets[nvidia]="nvc nvc++ nvfortran"
- sets[intel]="icc icpc ifort"
-sets[oneAPI]="icx icpx ifx"
-  sets[llvm]="clang clang++ flang"
-   sets[gcc]="gcc g++ gfortran"    #ALWAYS keep gcc last
+[[ ! $OS == darwin ]] && declare -A sets # Don't do on Darwin bash 3.2.57(1) (arm64-apple-darwin24)
+nvidia_set="nvc nvc++ nvfortran"
+ intel_set="icc icpc ifort"
+oneAPI_set="icx icpx ifx"
+  llvm_set="clang clang++ flang"
+  gcc_set="gcc g++ gfortran"      #Uh cannot use hash in Darwin bash!!!!!
+
+sets[nvidia]="$nvidia_set"
+ sets[intel]="$intel_set"
+sets[oneAPI]="$oneAPI_set"
+  sets[llvm]="$llvm_set"
+   sets[gcc]="$gcc_set"    #ALWAYS keep gcc last
 
 
 #Check for all known compilers
 echo "COMPILERS Searching Compiler Families (${compiler_families[@]})"
 
 for family in ${compiler_families[@]}; do
-  set=( ${sets[$family]} )
+
+  [[ $OS != darwin ]] && set=( ${sets[$family]} )
+  if [[ $OS == darwin ]]; then
+     [[ $family == nvidia ]] && set=("$nvidia_set")
+     [[ $family == intel  ]] && set=("$intel_set")
+     [[ $family == oneAPI ]] && set=("$oneAPI_set")
+     [[ $family == llvm   ]] && set=("$llvm_set")
+     [[ $family == gcc    ]] && set=("$gcc_set")
+  fi 
+
   found=()
   for compiler in ${set[@]}; do
       output=`type $compiler 2>&1`
@@ -47,7 +83,7 @@ for family in ${compiler_families[@]}; do
     flat_set="${set[@]}"
   if [[ ${#found[@]} == 0 ]]; then
      if [[ $O == V ]]; then
-       printf " %-6s family NOT AVAILABLE in present module environment.\n" $family
+       printf " %-6s family NOT AVAILABLE $module_clause.\n" $family
        [[ $family == gcc ]] && printf "       family is required!\n"  && STATUS=1
      fi
      [[ $family == gcc ]] && found_gcc_family=no
@@ -55,8 +91,8 @@ for family in ${compiler_families[@]}; do
 
   if [[ ${#found[@]} == 1 ]] || [[ ${#found[@]} == 2 ]]; then
      if [[ $O == N ]] || [[ $O == V ]]; then
-       printf " %-6s family SUBSET AVAILABLE in present module environment (%s).\n"  $family  "$flat_found"
-       [[ $family == gcc ]] && printf "       Complete family is required!\n" "$flat_set"  && STATUS=1
+       printf " %-6s family SUBSET AVAILABLE $module_clause (%s).\n"  $family  "$flat_found"
+       [[ $family == gcc ]] && printf "        Complete family is required!\n" "$flat_set"  && STATUS=1
      fi
      [[ $family == gcc ]] && found_gcc_subset=yes && gcc_subset=($flat_found)
      found_subsets+=("${family}: $flat_found")
@@ -64,12 +100,16 @@ for family in ${compiler_families[@]}; do
 
   if [[ ${#found[@]} == 3 ]] || [[ ${#found[@]} == 1 ]]; then
      if [[ $O == N ]] || [[ $O == V ]]; then
-       printf ' %-6s family in present module environment (%s).\n' $family  "$flat_found"
+       printf ' %-6s family $module_clause (%s).\n' $family  "$flat_found"
      fi
      found_all_3+=("${family}: $flat_found") 
   fi
 
-  if [[ ${compiler_families[-1]} == $family ]]; then
+##version 3.2.57(1)-release (arm64-apple-darwin24) doesn't like ${x[-1]} for last variable.
+   last_id=$(( ${#compiler_families[@]} - 1))
+
+##if [[ ${compiler_families[-1]} == $family ]]; then
+  if [[ ${compiler_families[$last_id]} == $family ]]; then
     if [[ $O == T ]]; then
       if [[ ${#found_subsets[@]} == 0 ]] && [[ ${#found_all_3[@]} == 0 ]];  then
         echo " COMPILERS NONE FOUND (searched ${compiler_families[@]})"
diff --git a/06_Allocations b/06_Allocations
--- a/06_Allocations
+++ b/06_Allocations
@@ -5,11 +5,30 @@
 [[ $1 == v ]] && O=V 
 
 STATUS=0
+  HPC_OSs=(rocky centos fedora ubuntu debian)
+  if [[ -f /etc/os-release ]]; then
+    output=$( grep ^ID= /etc/os-release ) #e.g. ID="rocky"
+    eval $output
+    OS=$ID
+    if [[ ! $HPC_OSs =~ $OS ]]; then
+       echo " internal ERROR: could not get OS from /etc/os-release"
+       echo "   search list ( ${HPC_OSs[@]} )"
+       exit 1
+    fi
+  else
+    [[ `uname -a` =~ Darwin ]] && OS=darwin
+  fi
 
-host_name=`hostname -A`
+  [[ $OS == darwin ]]          && opts='-s'
+  [[ ${HPC_OSs[@]} =~ $OS   ]] && opts='-A'
+
+  host_name=`hostname $opts`
+
 for sys in frontera vista stampede ls6; do
   [[ $host_name =~ $sys ]] && AT_TACC=yes TACC_SYS=$sys
 done
+
+[[ $AT_TACC != yes ]] && echo " ALLOCATIONS" && echo " NONE programmed for this systems." && exit 0
 
                   #milfeld:*:1117:825112:milfeld:/home1/00770/milfeld:/bin/bash
 user_info=`getent passwd $USER`
diff --git a/08_Reservations b/08_Reservations
--- a/08_Reservations
+++ b/08_Reservations
@@ -25,11 +25,33 @@
   [[ $1 == t ]] && O=T
   [[ $1 == v ]] && O=V
 
-  host_name=`hostname -A`
+  HPC_OSs=(rocky centos fedora ubuntu debian)
+  if [[ -f /etc/os-release ]]; then
+    output=$( grep ^ID= /etc/os-release ) #e.g. ID="rocky"
+    eval $output
+    OS=$ID
+    if [[ ! $HPC_OSs =~ $OS ]]; then
+       echo " internal ERROR: could not get OS from /etc/os-release"
+       echo "   search list ( ${HPC_OSs[@]} )"
+       exit 1
+    fi
+  else
+    [[ `uname -a` =~ Darwin ]] && OS=darwin
+  fi
+
+  [[ $OS == darwin ]]          && opts='-s'
+  [[ ${HPC_OSs[@]} =~ $OS   ]] && opts='-A'
+
+  host_name=`hostname $opts`
   for sys in frontera vista stampede ls6; do
     [[ $host_name =~ $sys ]] && AT_TACC=yes TACC_SYS=$sys
   done
 
+if [[ ! $AT_TACC == yes ]]; then
+  echo " BATCH RESERVATIONS" && echo " Checklist not configured for this system." && exit 0
+fi
+
+# PROJECT INFORMATION
 if [[ $AT_TACC == yes ]]; then
                        TACC_ACC_DIR="/usr/local/etc/"
   [[ $sys == ls4 ]] && TACC_ACC_DIR=/sge_common/default/acct/map/
diff --git a/09_Blocked_users b/09_Blocked_users
--- a/09_Blocked_users
+++ b/09_Blocked_users
@@ -15,10 +15,29 @@
 
 STATUS=0
 
-host_name=`hostname -A`
-for sys in frontera vista stampede ls6; do
-  [[ $host_name =~ $sys ]] && AT_TACC=yes TACC_SYS=$sys
-done
+  HPC_OSs=(rocky centos fedora ubuntu debian)
+  if [[ -f /etc/os-release ]]; then
+    output=$( grep ^ID= /etc/os-release ) #e.g. ID="rocky"
+    eval $output
+    OS=$ID
+    if [[ ! $HPC_OSs =~ $OS ]]; then
+       echo " internal ERROR: could not get OS from /etc/os-release"
+       echo "   search list ( ${HPC_OSs[@]} )"
+       exit 1
+    fi
+  else
+    [[ `uname -a` =~ Darwin ]] && OS=darwin
+  fi
+
+  [[ $OS == darwin ]]          && opts='-s'
+  [[ ${HPC_OSs[@]} =~ $OS   ]] && opts='-A'
+  host_name=`hostname $opts`
+
+  for sys in frontera vista stampede ls6; do
+    [[ $host_name =~ $sys ]] && AT_TACC=yes TACC_SYS=$sys
+  done
+  [[ $AT_TACC != yes ]] && echo " RESERVATIONS" &&  
+     echo " Checklist not configured for Reservations on this system." && exit 0
 
 if [[ $AT_TACC == yes ]]; then
   ACL_DIR=/etc/slurm
