Added verbosity to 05_Compilers and checklist.sh scripts.

diff --git a/05_Compilers b/05_Compilers
--- a/05_Compilers
+++ b/05_Compilers
@@ -21,7 +21,7 @@ for sys in frontera vista stampede ls6; do
   [[ $host_name =~ $sys ]] && AT_TACC=yes TACC_SYS=$sys
 done
 
-compiler_families=( nvidia intel oneAPI llvm gcc)
+compiler_families=(nvidia intel oneAPI llvm gcc)
 
 declare -A sets
 sets[nvidia]="nvc nvc++ nvfortran"
@@ -32,7 +32,7 @@ sets[oneAPI]="icx icpx ifx"
 
 
 #Check for all known compilers
-echo "Searching for Compiler Families (complete sets: C/C++/Fortran)"
+echo "COMPILERS Searching Compiler Families (${compiler_families[@]})"
 tab=$space
 
 for family in ${compiler_families[@]}; do
@@ -48,18 +48,52 @@ for family in ${compiler_families[@]}; do
   flat_found="${found[@]}"
     flat_set="${set[@]}"
   if [[ ${#found[@]} == 0 ]]; then
-     printf "%s %-6s family    NOT AVAILABLE in present module environment.\n"       "$tab" $family
-     [[ $family == gcc ]] && printf "%s       family is required!\n" "         $tab" && STATUS=1
+     if [[ $O == V ]]; then
+       printf "%s %-6s family NOT AVAILABLE in present module environment.\n" "$tab" $family
+       [[ $family == gcc ]] && printf "%s       family is required!\n" "$tab" && STATUS=1
+     fi
+     [[ $family == gcc ]] && found_gcc_family=no
   fi
 
   if [[ ${#found[@]} == 1 ]] || [[ ${#found[@]} == 2 ]]; then
-     printf "%s %-6s family SUBSET AVAILABLE in present module environment (%s).\n"  "$tab"  $family  "$flat_found"
-     [[ $family == gcc ]] && printf "%s       Complete family is required!\n" "$tab" "$flat_set"  && STATUS=1
+     if [[ $O == N ]] || [[ $O == V ]]; then
+       printf "%s %-6s family SUBSET AVAILABLE in present module environment (%s).\n"  "$tab"  $family  "$flat_found"
+       [[ $family == gcc ]] && printf "%s       Complete family is required!\n" "$tab" "$flat_set"  && STATUS=1
+     fi
+     [[ $family == gcc ]] && found_gcc_subset=yes && gcc_subset=($flat_found)
+     found_subsets+=("${family}: $flat_found")
   fi
 
   if [[ ${#found[@]} == 3 ]] || [[ ${#found[@]} == 1 ]]; then
-     printf '%s %-6s family    ALL AVAILABLE in present module environment (%s).\n'  "$tab"  $family  "$flat_found"
+     if [[ $O == N ]] || [[ $O == V ]]; then
+       printf '%s %-6s family in present module environment (%s).\n'  "$tab"  $family  "$flat_found"
+     fi
+     found_all_3+=("${family}: $flat_found") 
   fi
+
+  if [[ ${compiler_families[-1]} == $family ]]; then
+    if [[ $O == T ]]; then
+      if [[ ${#found_subsets[@]} == 0 ]] && [[ ${#found_all_3[@]} == 0 ]];  then
+        echo "$tab COMPILERS NONE FOUND (searched ${compiler_families[@]})"
+        exit 1
+      fi
+      if [[ $found_gcc_family == no ]]; then
+        echo "$tab COMPILERS GCC compilers not present."
+        exit 1
+      fi
+      if [[ $found_gcc_subset == yes ]]; then
+        echo "$tab COMPILERS Only subset of GCC compilers found ($gcc_subset)."
+        exit 1
+      fi
+      if [[ ${#found_all_3[@]} == 0 ]]; then
+        echo "$tab COMPILERS No complete complier set found. (Incomplete sets: ${found_subsets[@]})"
+        exit 1
+      fi
+      [[ ${#found_subsets[@]} -gt 0 ]] && FSETS="${found_subsets[@]}" && echo HERE9
+      echo "$tab COMPILERS ${found_all_3[@]} $FSETS" #(subsets: ${found_subsets[@]})
+    fi 
+  fi
+
 done
 
 exit $STATUS
